name: Create Randomized Platinum
on: 
  workflow_dispatch:
    inputs:
      "Output File Name":
        description: "The name of the file containing the randomized rom"

jobs:
    create-randomized-platinum:
      runs-on: ubuntu-latest
      steps:
        - name: Generate execution variables
          id: variables
          run: |
            # Set flavor
            FLAVOR="platinum"
            echo "FLAVOR=$FLAVOR" >> "$GITHUB_OUTPUT"
            echo "flavor = $FLAVOR"

            # Set extension
            EXTENSION=".nds"
            echo "EXTENSION=$EXTENSION" >> "$GITHUB_OUTPUT"
            echo "extension = $EXTENSION"

            # Generate datenow
            DATENOW="$(date +'%Y-%m-%d-%s.%N')"
            echo "DATENOW=$DATENOW" >> "$GITHUB_OUTPUT"
            echo "date now = $DATENOW"

            # Generate zipname
            ZIPNAME="randomized-${FLAVOR}${DATENOW}.zip"
            echo "ZIPNAME=$ZIPNAME" >> "$GITHUB_OUTPUT"
            echo "zip name = $ZIPNAME"

            # Handle outputfilename input
            OUTFILENAME="${{ github.event.inputs['Output File Name'] }}$EXTENSION"
            # If input is empty, use zipname
            if [ -z "$OUTFILENAME" ]; then
              OUTFILENAME="$ZIPNAME$EXTENSION"
            else
              # Otherwise, use input
              echo "OUTFILENAME=$OUTFILENAME$EXTENSION" >> GITHUB_OUTPUT
              # Update zip name as well
              echo "ZIPNAME=randomized-${FLAVOR}${DATENOW}[$OUTFILENAME].zip"
            fi
            echo "$OUTFILENAME"
            echo "$ZIPNAME"

        - uses: actions/checkout@v4
        - run: |
            mkdir -p ./original
            wget -O ./original/rom.zip '${{ vars.BASEPATH }}${{ vars.PLATINUM }}'
            unzip ./original/rom.zip -d ./original
            mv './original/Pokemon - Platinum Version (USA) (Rev 1)${{ steps.variables.outputs.EXTENSION }}' ./original/rom${{ steps.variables.outputs.EXTENSION }}
        - name: Setup java
          uses: actions/setup-java@v4
          with:
            distribution: 'oracle'
            java-version: '21'
        - run: java -jar ./universalpokemonrandomizer/PokeRandoZX.jar cli -i ./original/rom${{ steps.variables.outputs.EXTENSION }} -o ./randomized/${{ steps.variables.outputs.OUTPUTFILENAME }} -s ./universalpokemonrandomizer/Original_Settings_gen1-6.rnqs -l
        - run: cd ./randomized && zip ${{ steps.variables.outputs.ZIPNAME }}.zip ${{ steps.variables.outputs.OUTPUTFILENAME }} && rm -f ${{ steps.variables.outputs.OUTPUTFILENAME}}
        - run: |
            rm -rf ./original
            mkdir -p ./randomized/${{ steps.variables.outputs.FLAVOR }}
            mv ./randomized/${{ steps.variables.outputs.OUTPUTFILENAME }}.log ./randomized/${{ steps.variables.outputs.FLAVOR }}/${{ steps.variables.outputs.OUTPUTFILENAME }}.log
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        
        - name: Install dependencies
          run: pip install google-api-python-client google-auth
        - run: ls -la
        - name: Upload to Google Drive
          env:
            FOLDER_ID: ${{ secrets.PLATINUM_FOLDER_ID }}
            REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            ZIP_NAME: ${{ steps.variables.outputs.ZIPNAME }}
          run: |
            python << 'EOF'
            import os
            from google.oauth2.credentials import Credentials
            from googleapiclient.discovery import build
            from googleapiclient.http import MediaFileUpload

            creds = Credentials(
                token = None,
                refresh_token = os.environ.get("REFRESH_TOKEN"),
                token_uri = "https://oauth2.googleapis.com/token",
                client_id = os.environ.get("CLIENT_ID"),
                client_secret = os.environ.get("CLIENT_SECRET"),
                scopes = ["https://www.googleapis.com/auth/drive"]
            )

            service = build("drive", "v3", credentials=creds)

            zip_name = os.environ.get("ZIP_NAME")

            file_metadata = {
                "name": zip_name,
                "parents": [os.environ.get("FOLDER_ID")] if os.environ.get("FOLDER_ID") else []
            }

            folder = service.files().get(
                fileId = os.environ.get("FOLDER_ID") if os.environ.get("FOLDER_ID") else "",
                fields = "id, name, mimeType"
            ).execute()

            media = MediaFileUpload("./randomized/" + zip_name, mimetype = "application/zip")

            service.files().create(
                body = file_metadata,
                media_body = media,
                fields = "id"
            ).execute()
            EOF
        - run: rm -f ./randomized/${{ steps.variables.outputs.ZIPNAME }}
        - name: Commit & Push changes
          uses: actions-js/push@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: 'main'